### ISSUE TITLE
yarn run start能运行出来， 但期间有[extHost:error] [extHost:error]，用管理员powerShell一样

### ISSUE THREAD

**Issue by kavil** [opensumi/ide-electron#24]
`$ yarn run start
yarn run v1.22.19
$ electron --inspect=9229 .

Debugger listening on ws://127.0.0.1:9229/e9403642-5418-4069-8093-b6ab85beb808
For help, see: https://nodejs.org/en/docs/inspector
processArgv [
  'D:\\playtime\\sumie\\node_modules\\electron\\dist\\electron.exe',
  '--inspect=9229',
  '.'
]
馃殌 ~ file: index.ts ~ line 17 ~ launchFromCommandLine ~ argv []
working directory D:\playtime\sumie
workspace undefined
[node]listenPath \\.\pipe\sumi-ipc-electron-windowZAOKJBu6oQqvZdef1I9M_
[node]server listen on path \\.\pipe\sumi-ipc-electron-windowZAOKJBu6oQqvZdef1I9M_
ready
[node][extHost:error] [extHost:error] [Extension-Host] Failed opening file C:\Users\kaipc\.sumi-oss\logs\20220619\extHost.log for writing: Permission denied

Error: Failed opening file C:\Users\kaipc\.sumi-oss\logs\20220619\extHost.log for writing: Permission denied
    at createRotatingLogger (D:\playtime\sumie\node_modules\spdlog\index.js:34:9)
    at D:\playtime\sumie\node_modules\spdlog\index.js:27:7
    at D:\playtime\sumie\node_modules\mkdirp\index.js:51:26
    at FSReqCallbac...[node]listenPath \\.\pipe\sumi-ipc-electron-windowfy0gn-gietgHBivPhRyL0
[node]server listen on path \\.\pipe\sumi-ipc-electron-windowfy0gn-gietgHBivPhRyL0
ready
[node][extHost:error] [extHost:error] [Extension-Host] Failed opening file C:\Users\kaipc\.sumi-oss\logs\20220619\extHost.log for writing: Permission denied

Error: Failed opening file C:\Users\kaipc\.sumi-oss\logs\20220619\extHost.log for writing: Permission denied
    at createRotatingLogger (D:\playtime\sumie\node_modules\spdlog\index.js:34:9)
    at D:\playtime\sumie\node_modules\spdlog\index.js:27:7
    at D:\playtime\sumie\node_modules\mkdirp\index.js:51:26
    at FSReqCallbac...[node][extHost:error] [extHost:error] [Extension-Host] 娌℃湁鎵惧埌 Symbol(TestService) 鐨?Provider 

Error: 娌℃湁鎵惧埌 Symbol(TestService) 鐨?Provider
    at Object.noProviderError (file:///D:/playtime/sumie/app/browser/bundle.js:3005:12)
    at Injector.__webpack_modules__../node_modules/@opensumi/di/dist/injector.js.Injector.get (file:///D:/playtime/sumie/app/browser/bundle.js:4469:33)     
    at MainThreadTestsImpl.get [as testService] (file:///D:/playtime/sumie/app/browser/bundle.js:2810:51)
    at...[node][extHost:error] [extHost:error] [Extension-Host] 娌℃湁鎵惧埌 Symbol(TestService) 鐨?Provider 

Error: 娌℃湁鎵惧埌 Symbol(TestService) 鐨?Provider
    at Object.noProviderError (file:///D:/playtime/sumie/app/browser/bundle.js:3005:12)
    at Injector.__webpack_modules__../node_modules/@opensumi/di/dist/injector.js.Injector.get (file:///D:/playtime/sumie/app/browser/bundle.js:4469:33)     
    at MainThreadTestsImpl.get [as testService] (file:///D:/playtime/sumie/app/browser/bundle.js:2810:51)
    at...[node][extHost:error] [extHost:error] Error: Should provide a name inside candidate fieldError: Should provide a name inside candidate field
        at Function.validate (D:\playtime\sumie\app\extension\index.js:13456:19)
        at new DocumentSymbol (D:\playtime\sumie\app\extension\index.js:13452:26)
        at new DocumentSymbol (D:\playtime\sumie\app\extension\index.js:42117:24)
        at asDocumentSymbol (D:\playtime\sumie\extensions\robocorp.robotframework-lsp-0.48.2\node_modules\vscode-languageclient\li...[node][extHost:error] [extHost:error] [Extension-Host] 娌℃湁鎵惧埌 Symbol(TestService) 鐨?Provider `

**Comment by yantze** [comment]
`Error: 娌℃湁鎵惧埌 Symbol(TestService) 鐨?Provider` 看起来是你的 TestService 没有注册成功，可以在命令行执行 chcp 65001 显示一下中文。

` Failed opening file C:\Users\kaipc.sumi-oss\logs\20220619\extHost.log for writing: Permission denied ` 这个不影响，计划在修复这个权限问题。
