### ISSUE TITLE
安装Diff & Merge插件，选择2个文件diff的时候（choose a file to merge），提示Error: command 。

### ISSUE THREAD

**Issue by quick123official** [opensumi/ide-electron#40]
**描述你的问题（Describe the bug）**
安装Diff & Merge插件，选择2个文件diff的时候（choose a file to merge），提示Error: command 。

错误信息：
[browser:error] Error: command 'workbench.action.generateColorTheme' not found
    at StandaloneCommandService.executeCommand (bundle.js:323041:35)
    at MonacoCommandService.executeCommand (bundle.js:80233:39)
    at async MainThreadCommands.$executeCommand (bundle.js:96820:20)
DebugLog.error @ bundle.js:54494
error @ bundle.js:125702
error @ bundle.js:37445
$executeCommand @ bundle.js:96823
await in $executeCommand (async)
$executeCommandWithExtensionInfo @ bundle.js:96816
_doInvokeHandler @ bundle.js:20825
await in _doInvokeHandler (async)
_invokeHandler @ bundle.js:20810
_receiveRequest @ bundle.js:20797
_receiveOneMessage @ bundle.js:20746
(anonymous) @ bundle.js:20697
fire @ bundle.js:173930
(anonymous) @ bundle.js:90522
onNotification @ bundle.js:20534
(anonymous) @ bundle.js:20476
handleNotification @ bundle.js:339966
processMessageQueue @ bundle.js:339690
(anonymous) @ bundle.js:339677
processImmediate @ node:internal/timers:464

**预期表现（Expected behavior）**

正常diff && merge

**问题截图（Screenshots）**
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/58046636/180611712-cf6226ef-a65f-4af9-91a3-af87fc9fbb80.png">

**环境信息（Environment）**

- OS: macOS 12.4 非 arm
- Browser: electron
- OpenSumi Version: 2.18.15

**补充信息（Additional context）**

无

**Comment by quick123official** [comment]
@yantze

**Comment by yantze** [comment]
看看来是 OpenSumi 内部没有实现这个 command，暂时不兼容，其它 Merge 方法是好的吧

**Comment by yantze** [comment]
似乎 Diff & Merge 这个插件没有识别到选择两个文件的场景： @erha19   

OpenSumi 的右键菜单：
<img width="381" alt="image" src="https://user-images.githubusercontent.com/2226423/180906688-f28a603c-efec-4979-a73b-4220c8094d96.png">


VSCode 的y右键菜单：
<img width="521" alt="image" src="https://user-images.githubusercontent.com/2226423/180906715-6398a22f-d574-4fb2-8d20-f3aa48e855f9.png">

**Comment by erha19** [comment]
多选的适配我来看一下

**Comment by yantze** [comment]
OpenSumi 内置的 Compare with Current File 已经支持 Diff & Merge 的功能，考虑到实现 `workbench.action.generateColorTheme` 需要一定的时间，先记为一个 issue，先放进排期。

**Comment by quick123official** [comment]
收到，感谢！

**Comment by quick123official** [comment]
看了一下，Compare with Current File 这个功能不是很理想。1. 没有Merge的能力；2. 不能选中2个文件进行对比。
